## Recuperar todas las peliculas
GET http://localhost:3000/movies

## Recuperar una pelicula por id
GET http://localhost:3000/movies/1

## Recuperar todas las peliculas por género
GET http://localhost:3000/movies?genre=terror
